- name: create ec2 and r53
  hosts: local
  connection: local
  vars:
    ami_id: ami-09c813fb71547fc4f
    sg_id: sg-052879cc69a4a54b5
    zone_id: "Z09617511B5QP2P5E3AO"
    domain_name: "madhan66.store"
    instances:
    - mongodb

  tasks:
  - name: create ec2 instance
    amazon.aws.ec2_instance:
       name: "{{ itam }}"
       instance_type: t3.micro
       security_group: "{{ sg_id }}"
       image_id: "{{ ami_id }}"
       tags:
         name: "{{ itam }}"
    loop: "{{ instances }}"
    register: ec2_output

  - name: print the ec2_output
    ansible.builtin.debug:
      msg: "{{ ec2_output }}"